% DEFAULT CONFIGURATIONS
% --------------------------------------------------------------------
%                               LASER
%   Wavelength                    | wlen            | 780nm
%   Repetition rate               | T               | 12.5ns
%   Average power                 | P               | 180mW
%   Radius half width             | R_3db           | 5um
%   Pulse half width power (FWHM) | tau_p           | 100fs
% --------------------------------------------------------------------
%                                GaAs
%   Carrier recombination time    | tau_rec         | 300fs
%   Carrier scattering time       | tau_s           | 8.5fs
%   Dielectric constant           | er              | 12.96
%   Electron effective mass       | me_coef         | 0.067
%   Absorption coefficient        | absorp_len      | 1um
%   Dimensions [Wx Wy Wz]         | dimensions      | [10um 10um 2um]

laser_config = struct( ...
    'wlen', 780 * 1e-9, ...
    'T', 12.5 * 1e-9, ...
    'P', 180 * 1e-3, ...
    'R_3db', 5 * 1e-6, ...
    'tau_p', 100 * 1e-15 ...
    );

GaAs_config = struct( ...
    'dimensions', [10 10 2] * 1e-6, ...
    'er', 12.96, ...
    'tau_rec', 300 * 1e-15, ...
    'tau_s', 8.5 * 1e-15, ...
    'me_coef', 0.067, ...
    'absorp_len', 1 * 1e-6 ...
    );
