% DEFAULT CONFIGURATIONS
% ------------------------------------------------------------
%                           LASER
%   Wavelength                    | wlen            | 780nm
%   Repetition rate               | T               | 12.5ns
%   Average power                 | P               | 180mW
%   Radius half width             | R_3db           | 5um
%   Pulse half width power (FWHM) | tau_p           | 100fs
% ------------------------------------------------------------
%                           GaAs
%   Carrier recombination time    | rec_time        | 300fs
%   Carrier scattering time       | scat_time       | 8.5fs
%   Dielectric constant           | rel_permit      | 12.96
%   Electron effective mass       | electr_eff_mass | 0.067
%   Absorption coefficient        | absorp_coeff    | 1um
%   Dimensions [Wx Wy Wz]         | dimens          | [10um 10um 2um]

laser_config = struct( ...
    'wlen', 780 * 1e-9, ...
    'T', 12.5 * 1e-9, ...
    'P', 180 * 1e-3, ...
    'R_3db', 5 * 1e-6, ...
    'tau_p', 100 * 1e-15 ...
    );

GaAs_photoconductor_config = struct( ...
    'rec_time', 300 * 1e-15, ...
    'scat_time', 8.5 * 1e-15, ...
    'rel_permit', 12.96, ...
    'electr_eff_mass_coeff', 0.067, ...
    'absorp_coeff', 1 * 1e-6, ...
    'dimens', [10 * 1e-6 10 * 1e-6 2 * 1e-6] ...
    );
